
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from PIL import Image
from login import login
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Toplevel


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets/intro")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def intro():
    INTRO()

class INTRO(Toplevel):
    def loginPage(self):
        self.destroy()
        login()

    def __init__(self, *args, **kwargs):
        Toplevel.__init__(self, *args, **kwargs)

        self.geometry("360x700")
        self.configure(bg = "#06422C")

        self.canvas = Canvas(
            self,
            bg = "#06422C",
            height = 800,
            width = 360,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        file = relative_to_assets("image_1.gif")
        info = Image.open(file)
        frames = info.n_frames
        print(frames)

        self.canvas.place(x = 0, y = 0)
        im = []

        for i in range(frames):
            image_image_1 = PhotoImage(
                file=file, format=f'gif -index {70}'
            )   
            image_1 = self.canvas.create_image(
                180.0,
                400.0,
                image=image_image_1
            )

        image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = self.canvas.create_image(
            202.0,
            190.0,
            image=image_image_2
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png")
        )
        button_1 = Button(
            self.canvas,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.loginPage(),
            relief="flat"
        )
        button_1.place(
            x=68.0,
            y=580.0,
            width=225.0,
            height=70.0
        )
        self.resizable(False, False)
        self.mainloop()
